### ISSUE TITLE
Challenges with Conformance: Goals section point #1 needs breaking down for readability

### ISSUE THREAD

**Issue by maryjom** [w3c/wcag#1106]
Editorial comment - I had to read the Goals list item #1 several times to attempt to understand it. Having a single sentence that is multiple lines long is extremely difficult to parse.

**Comment by mbgower** [comment]
@maryjom I cannot locate the material you are referencing. I believe it has been addressed in the [WCAG 2.2 document](https://www.w3.org/TR/WCAG22/#conformance)? If so, please close this.

**Comment by maryjom** [comment]
@mbgower This was a comment on the Challenges with Conformance document's [section on Goals](https://www.w3.org/TR/accessibility-conformance-challenges/#goal), content and not WCAG 2.2. When I put in the number 1 in my comment, I didn't realize at the time that GitHub was attaching that to Issue number 1 which is not related in any way to my comment.  This sentence I had commented on still exists - item number 1 in the list in that section.

**Comment by patrickhlauke** [comment]
is this something we want to tackle in the WCAG 2.x backlog TF? feels like a more AGWG-general concern. what's the plan/status of the conformance challenges document?
