### ISSUE TITLE
Understanding links to Techniques and Failures documents are broken

### ISSUE THREAD

**Issue by fstrr** [w3c/wcag#3445]
It seems like links from Understanding documents to Techniques are broken. For example:

- [Motion Actuation Understanding](https://www.w3.org/WAI/WCAG22/Understanding/motion-actuation.html) Technique and Failure
- [Target Size Minimum](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html) link to C42
- [Keyboard](https://www.w3.org/WAI/WCAG22/Understanding/keyboard.html) - all the techniques and failures
- [Bypass Blocks](https://www.w3.org/WAI/WCAG22/Understanding/bypass-blocks.html) - all the Techniques
- [Focus Not Obscured](https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum.html) - link to Technique

**Comment by iadawn** [comment]
Should be fixed now

**Comment by fstrr** [comment]
Thanks, Kevin. Super speedy :)

Quick question: [Focus Not Obscured (Min)](https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum.html) links to an old version of [C43](https://www.w3.org/WAI/WCAG22/Techniques/css/C43) that was [replaced last month](https://github.com/w3c/wcag/tree/main/techniques/css). Is there a reason that the old version is still hanging around?
